### ISSUE TITLE
Type error when using latest HomeBridge

### ISSUE THREAD

**Issue by trgregg** [dsully/homebridge-pixelblaze#1]
**Describe The Bug:**
Homebridge throws a type error for this plugin and continuously restarts the child bridge.

**To Reproduce:**
Happens immediately upon start of Homebridge

**Expected behavior:**
Expect the plugin to no throw a TypeError. :-P

**Logs:**

```
typeerror: this.log is not a function    
at WebSocket.error (/usr/lib/node_modules/homebridge/src/logger.ts:139:10)    
at WebSocket.emit (node:events:527:28)    
at emitErrorAndClose (/usr/lib/node_modules/homebridge-pixelblaze/node_modules/ws/lib/websocket.js:895:13)    
at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-pixelblaze/node_modules/ws/lib/websocket.js:752:5)    
at ClientRequest.emit (node:events:527:28)    
at Socket.socketErrorListener (node:_http_client:454:9)    
at Socket.emit (node:events:527:28)    
at emitErrorNT (node:internal/streams/destroy:157:8)    
at emitErrorCloseNT (node:internal/streams/destroy:122:3)    
at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Plugin Config:**

```json
 {   "name": "Pixelblaze_Basement",
    "colorpicker": "7",
    "_bridge": {
        "username": "0E:91:EE:74:25:89",
        "port": 37348
    },
    "platform": "Pixelblaze"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-pixelblaze v1.1.1
* **Homebridge Version**: v1.6.0
* **Node.js Version**: v16.16.0
* **NPM Version**: 
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by dsully** [comment]
Hi - that doesn't appear to be a bug in this module, as the error is coming from `homebridge` itself.

Are you using the latest version?

**Comment by trgregg** [comment]
Homebridge Version v1.6.0 appears to be the latest.
FWIW, Other plugins do not get this error.

**Comment by dsully** [comment]
Ok. I'll have to take a look later / this weekend.

**Comment by trgregg** [comment]
Workaround: Using a child bridge seems to make this error go away.

**Comment by dsully** [comment]
Good to know. That's how I run all my plugins, which is why I've not seen this before.
